pub const SCREEN_WIDTH: i32 = 1024;
pub const SCREEN_HEIGHT: i32 = 512;
pub const CELL_SIZE: i32 = 4;
pub const COLUMN_COUNT: i32 = SCREEN_WIDTH / CELL_SIZE;
pub const ROW_COUNT: i32 = SCREEN_HEIGHT / CELL_SIZE;
